#!/bin/bash

# setup Shutdown Monitor mechanism
# Venus OS provides a restart command but not a shutdown command
# This modificaiton adds a shutdown command to the Device List / Settings / General menu
#
#	for RPI only a GPIO pin can also trigger shutdown

# tell CommonResources to:
#	prompt for install/uninstall
#	auto install or auto uninstall
#	then exit
#	IncludeHelpers will NOT return here !

standardPromptAndActions='yes'

#### following lines incorporate helper resources into this script
pkgDir=$( dirname $0 )
pkgName=$( basename $pkgDir )
pkgRoot=$( dirname $pkgDir )
if [ -e "$pkgDir/HelperResources/IncludeHelpers" ]; then
	source "$pkgDir/HelperResources/IncludeHelpers"
elif [ -e "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers" ]; then
	source "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers"
else
	echo "$pkgName: helper files not found - can't continue" | tee -a "/data/log/SetupHelper"
	exit 1
fi
#### end of lines to include helper resources


