#!/bin/bash


# This modificaiton adds support for an external transfer switch ahead of the
# MultiPlus inverter/charger AC input so that both grid and generator may be used
# Quattros provide a second AC input and internal switching between them
# A Multi only has one AC input so grid/generator switching must occur
# up stream of the Multi's AC input
#

packageLogFile="/var/log/ExtTransferSwitch/current"

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.
    
source "/data/SetupHelper/CommonResources"

#### end of lines to include SetupHelper

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
    echo
    echo "The MultiTransferSwitch switches AC input parameters"
	echo "  between grid (shore) and generator"
	echo "Separte input source type and AC Input Current Limits are stored for each input"
	echo "A digital input tells this service which input is currently active"
	echo "The service then switches the AC 1 input between the two stored values"
    echo
    standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
    logMessage "++ Installing ExtTransferSwitch"

    updateActiveFile "/opt/victronenergy/gui/qml/PageDigitalInput.qml"
    updateActiveFile "/opt/victronenergy/gui/qml/MbItemDigitalInput.qml"
    updateActiveFile "/opt/victronenergy/dbus-digitalinputs/dbus_digitalinputs.py"
    updateActiveFile "/opt/victronenergy/dbus-modbustcp/attributes.csv"

    installService $packageName

    if $filesUpdated ; then
        restartGui=true
    fi
fi

# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling ExtTransferSwitch"

	restoreActiveFile "/opt/victronenergy/gui/qml/PageDigitalInput.qml"
	restoreActiveFile "/opt/victronenergy/gui/qml/MbItemDigitalInput.qml"
	restoreActiveFile "/opt/victronenergy/dbus-digitalinputs/dbus_digitalinputs.py"
	restoreActiveFile "/opt/victronenergy/dbus-modbustcp/attributes.csv"

    removeService $packageName
fi

if $filesUpdated ; then
    restartGui=true
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript


